#!/bin/bash
# -*- sh -*-

URL=http://rabbitmq.docker:15672/api

rabbitmq()
{
    curl -i -u guest:guest -H "content-type:application/json" "$@"

}

rabbitmq -XPUT $URL/vhosts/proca
rabbitmq -d '{"password":"proca", "tags":""}' -XPUT $URL/users/proca 
rabbitmq -d '{"configure":".*","write":".*","read":".*"}' -XPUT $URL/permissions/proca/proca


