#!/bin/bash

set -e
set -u

VOL=/tmp/proca-queue
mkdir $VOL || true
docker run -d --hostname rabbitmq.docker \
       --name rabbitmq \
       -v $VOL:/var/lib/rabbitmq \
       --net proca --ip 172.19.0.3 \
       rabbitmq:3-management "$@"

# rabbitmq management at port 15672
# rabbitmqadmin help:
# list users
# 


